name: Terraform Workflow

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  terraform-plan:
    name: 'Terraform Plan - ${{ github.repository }}'  # Using the repository name dynamically
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Terraform Initialize
        working-directory: ./terraform-infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform-infra
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform-infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -out=tfplan

  terraform-apply:
    name: 'Terraform Apply - ${{ github.repository }}'  # Using the repository name dynamically
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: terraform-plan  # Ensure this job runs only after the 'terraform-plan' job completes successfully.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Terraform Initialize
        working-directory: ./terraform-infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform-infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply --auto-approve

